luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

**1. Optimizing update scripts and adjusting storage locations  #1 
2. v2ray Add HTTP Obfuscation support
Fixes #6  
Fixes #24**

2.v2ray Add HTTP Obfuscation support

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/log.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server-config.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

**Port randomly generated by server
Fixes #25
Fixes #26
Fixes #27**

3.Port randomly generated by server

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/etc/config/shadowsocksr
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/bin/ssr-monitor
luci-app-ssr-plus/root/usr/bin/ssr-rules
luci-app-ssr-plus/root/usr/bin/ssr-switch
luci-app-ssr-plus/root/usr/share/shadowsocksr/gfw2ipset.sh

**Optimize code structure and optimize geting IP
Fixes #20
Fixes #39**

4.Optimize code structure and optimize geting IP

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/bin/ssr-monitor

fix work with haproxy

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

Fix kcptun stop bug

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

Repair server or port check

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Convert to UTF-8 encoding

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Adjust kcptun stop method
Fixes https://github.com/fw876/helloworld/commit/c62b7e538a3008ddfb0c2873992df10f900f70ba#commitcomment-39874155

Adjust kcptun stop method

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Fix Get IP Bug

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

https://github.com/Lienol/openwrt-package/pull/494
旧版SS URI 触发
测试用例(订阅内容)：
>c3M6Ly9ZV1Z6TFRFeU9DMWpabUk2VVdGNlJXUmpWR2RpTVRVNVFDUXFRREV3TXk0ME1TNHhNRFV1TlRJNk56QTBNZz09IyU0MFNTUlNVQi0lRTklQTYlOTklRTYlQjglQUZBMjYtJUU0JUJCJTk4JUU4JUI0JUI5U1NSJUU2JThFJUE4JUU4JThEJTkwJTNBdC5jbiUyRkVHSkl5cmw=

subscribe: fix ss parse error when password contain '@'

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

**Fix process daemon startup bug**

Fix process daemon startup bug

---

luci-app-ssr-plus/root/usr/bin/ssr-rules

fix #53 
I don't known why it can solve this problem, but it really works.

fix udpblocked at global proxy mode

---

luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus

**Modify file permissions in advance and cancel "uci-defaults" change permissions**

Modify file permissions in advance and cancel "uci-defaults" change permissions

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
luci-app-ssr-plus/root/usr/bin/ssr-switch
tcping/Makefile

Fixes #114
Fixes #134
Fixes #145

Replace tcpping with tcping

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua

**The problem of starting node twice is solved**

The problem of starting node twice is solved

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/genvlessconfig.lua

Add VLESS's XTLS feature support to luci-app-ssr-plus.

luci-app-ssr-plus: add VLESS XTLS support.

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/genvlessconfig.lua

This pull request allow user to customize the flow setting in VLESS, including xtls-rprx-origin, xtls-rprx-origin-udp443, xtls-rprx-direct, xtls-rprx-direct-udp443. Require v2ray v4.31.0+.

luci-app-ssr-plus: allow user to customize VLESS flow setting

---

naiveproxy/Makefile
naiveproxy/src/init_env.sh

- Add host dep: ncurses
- Call openwrt downloader to fetch dep files
Fixes: coolsnowwolf/lede#5694.
Signed-off-by: CN_SZTL <cnsztl@project-openwrt.eu.org>

naiveproxy: sync with upstream

---

luci-app-ssr-plus/root/usr/bin/ssr-rules

6. Fix getting lan name error Fixes #220

6. Fix getting lan name error Fixes

---

luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/bin/ssr-rules
luci-app-ssr-plus/root/usr/share/shadowsocksr/chinaipset.sh
luci-app-ssr-plus/root/usr/share/shadowsocksr/gfw2ipset.sh
luci-app-ssr-plus/root/usr/share/shadowsocksr/ssrplusupdate.sh
luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua

9. Fix processing dnsmasq and iptables bug Fixes #215 Fixes #176 Fixes #154

9. Fix processing dnsmasq and iptables bug

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2rayconfig.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/genvlessconfig.lua

5. Add mkcp obfuscated password Fixes #223

5. Add mkcp obfuscated password

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/root/etc/config/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua

3. gfwlist: add v2fly/domain-list

3. gfwlist: add v2fly/domain-list

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
luci-app-ssr-plus/root/lib/upgrade/keep.d/luci-app-ssr-plus

4. Fix configuration retention bug

4. Fix configuration retention bug

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua

add xtls-rprx-splice

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2config.lua

**Fix startup failure caused by mux of xtls**

Fix startup failure caused by mux of xtls

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/control.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/etc/config/shadowsocksr
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
luci-app-ssr-plus/root/usr/bin/ssr-rules

Add interface control options

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2config.lua

**Fix v2ray tcp>http and http2 configuration errors**

Fix v2ray tcp>http and http2 configuration errors

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2config.lua

Fixes #255
Fixes #260
Fixes #254 @z1790

Fix V2 TLS configuration servername issue

---

luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/bin/ssr-switch
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

Fix the problem of repeated startup when running
Fixes #225

Optimize start and fix some errors 

---

luci-app-ssr-plus/root/usr/bin/ssr-gfw

Fix gfwlist update errors

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

8. Fix udp local port and TCP local port duplication

8. Fix udp local port and TCP local port duplication

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2config.lua

Fix Global Socks server error

---

luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua

Fix the error that wss cannot connect when only using CDN IP
Fixes #284 
Fix the problem caused by https://github.com/openwrt/packages/pull/14257
Fixes #287 
Fixes #263

Fix the error that wss cannot connect when only using CDN IP

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

Fix configuration errors and trojan-go udp mode

---

luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/etc/init.d/shadowsocksr

ipt2socks replaces redsocks2

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua

Fixes #369

---

naiveproxy/patches/010-Fix-OpenWrt-x86-builds.patch

Fixes: coolsnowwolf/lede#6268
Signed-off-by: CN_SZTL <cnsztl@project-openwrt.eu.org>

naiveproxy: backport patch to fix building on x86 platform

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
luci-app-ssr-plus/root/usr/bin/ssr-monitor
luci-app-ssr-plus/root/usr/share/shadowsocksr/gfw2ipset.sh

**Add xray-plugin support
Remove obsolete patches**
Fixes #395

Add xray-plugin support

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
shadowsocks-rust/Makefile

How fast ss-rust is (aes-128-gcm, on NanoPi R2S with 1608MHz)?

shadowsocks-rust: add new package

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/init.d/shadowsocksr

luci-app-ssr-plus: fix typo err of binname

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua

国内CDN延迟更低
[https://github.com/fw876/helloworld/pull/427](https://github.com/fw876/helloworld/pull/427)

Replace CDN

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua

Change the display mode

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Fixes: #438

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr
shadowsocks-rust/Makefile

luci-app-ssr-plus: fix arguments for ss-rust

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Fixes: dc13501b721d78 ("luci-app-ssr-plus: move shadowsocks UDP argument to configuration")

luci-app-ssr-plus: re-append protocol arg for ss-rust

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

Finally fixed this... Fuck it!

luci-app-ssr-plus: move ss-rust hack to configuration

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Optimize user experience

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

Fixes: 530a31be6cb2e2 ("luci-app-ssr-plus: move ss-rust hack to configuration")
Closes: #476

luci-app-ssr-plus: correct protocol place for ss

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

They're totally unsafe, and deprecated in new designs.  
All of your data encrypted in these way could be replayed and decrypted.
For details, see:
https://shadowsocks.org/assets/whitepaper.pdf
https://phuker.github.io/shadowsocks-active-probing.html
https://github.com/edwardz246003/shadowsocks
- - -
Cc: @coolsnowwolf
Cc: @Mattraks

luci-app-ssr-plus: drop ss stream-cipher support

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
v2ray-core/Makefile
xray-core/Makefile

v2ray-core: add new package

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server-config.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server.lua
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
xray-core/Makefile

[RFC] luci-app-ssr-plus: add basic ss server support

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

luci-app-ssr-plus: avoid crash when ss encrypt method is stream-cipher

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
naiveproxy/Makefile
naiveproxy/patches/001-Remove-concurrency-limit.patch
naiveproxy/src/init_env.sh

Some proxies providers may use "simple-obfs" instead of "obfs-local",
make it compatible.

luci-app-ssr-plus: adapt simple-obfs plugin

---

naiveproxy/Makefile

naiveproxy: compat with stable version

---

luci-app-ssr-plus/root/usr/bin/ssr-rules

luci-app-ssr-plus: drop QUIC traffic

---

luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

luci-app-ssr-plus: fix parsing ss server_port

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

luci-app-ssr-plus: fix compatible with v2ray ss

---

luci-app-ssr-plus/po/zh-cn/ssr-plus.po

Solve the problem of inconsistency caused by missing "Apply" translation

Add translation

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

luci-app-ssr-plus: fix support for the real sip008 subscription

---

README.md

参考 https://github.com/coolsnowwolf/lede/issues/3642#issuecomment-596123091

readme 中增加添加 ucl upx 的说明。

---

luci-app-ssr-plus/luasrc/view/shadowsocksr/status.htm

Not running shows red, running shows green

luci-app-ssr-plus：adapter luci-theme-openwrt-2020 theme

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua

luci-app-ssr-plus: add xchacha20-ietf-poly1305 for *ray SS

---

hysteria/Makefile
hysteria/patches/010-feat-TCP-redirect-implementation.patch
hysteria/patches/020-fix-build-failure-on-linux-386.patch
luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

luci-app-ssr-plus: add hysteria support

---

xray-core/Makefile

xray-core: update to 1.5.10

---

xray-plugin/Makefile

xray-plugin: update to 1.5.10

---

v2ray-geodata/Makefile

v2ray-geodata: update version

---

luci-app-ssr-plus/po/zh-cn/ssr-plus.po

luci-app-ssr-plus: update Simplified Chinese translation

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

After the tuic's maintainer released the latest version 1.0.0, its configuration files format has made some changes.

update the configuration format of tuic latest release 1.0.0

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

remove all tuic-client nodes before testing. Welcome any feedback, good luck.

luci-app-ssr-plus: fix can't start other nodes if exist tuic-nodes

---

luci-app-ssr-plus/Makefile

luci: fix typo

---

mosdns/Makefile

- Add `mosdns` package for users who using official openwrt

mosdns: add new package

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

luci-app-ssr-plus: Repair `Hysteria2` version detection

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client.lua
luci-app-ssr-plus/root/etc/init.d/shadowsocksr

luci-app-ssr-plus: Enhance proxy port configuration with custom port support

luci-app-ssr-plus: Enhance proxy port configuration with custom port support

---

hysteria/Makefile

hysteria: fix compile error

---

xray-core/Makefile

Update xray-core 1.18.21

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

Fixed a subscription configuration import issue

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua

Fixed: https://github.com/fw876/helloworld/commit/96fff440034ecd4691c5e5437a1f76227c5f97ab

luci-app-ssr-plus: update.lua: fix typo erro.

---

shadowsocks-libev/Makefile
shadowsocks-libev/README.md
shadowsocks-libev/files/shadowsocks-libev.config
shadowsocks-libev/files/shadowsocks-libev.init
shadowsocks-libev/files/ss-rules/chain.uc
shadowsocks-libev/files/ss-rules/set.uc
shadowsocks-libev/files/ss-rules/ss-rules.uc
shadowsocks-libev/patches/100-Upgrade-PCRE-to-PCRE2.patch
shadowsocks-libev/patches/101-fix-mbedtls3.6-build.patch

兼容mbedtls2.28版本和mbedtls3.6.x版本。

shadowsocks-libev: Add new package.

---

chinadns-ng/Makefile

Retain armv5 version of 2024.10.14.

chinadns-ng: update to 2024.11.17

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua

luci-app-ssr-plus: Fix Importing configuration cannot import fingerprint.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/control.lua

修复：https://github.com/fw876/helloworld/issues/1574
**修改前：**

luci-app-ssr-plus: control.lua: Fix "Add or Remove" domain name list domain name click "Save and apply" pop-up "No changes to apply" box.

---

luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/log.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/backup_restore.htm
luci-app-ssr-plus/luasrc/view/shadowsocksr/log.htm
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po

*** 增加备份、恢复和重置功能后，在最新的数据库和较多节点情况下，不需再重新获取订阅并对软件重新设置以及重新进行数据库的更新，且可以在正常运行状态下备份，在恢复配置时自动运行。
**效果图：**

luci-app-ssr-plus: Add backup and restore and reset functions.

---

xray-core/Makefile

xray-core: update to 24.12.31

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/log.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/backup_restore.htm

luci-app-ssr-plus: optimize the backup and restore page.

---

luci-app-ssr-plus/root/usr/share/rpcd/acl.d/luci-app-ssr-plus.json

luci-app-ssr-plus: luci-app-ssr-plus.json: Fix `www/cgi-bin/luci` erro issues.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

luci-app-ssr-plus: Add separate Xudp mux for XHTTP and fixed vmess import sni issues.

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

luci-app-ssr-plus: optimize `Netflix` shunt value code.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

luci-app-ssr-plus: Fix `SS` node fails to import plug-ins.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

luci-app-ssr-plus: Resolve `ss` and `ss-rust` overlay display issues.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

1、修复 Hysteria2 订阅解析问题；
2、添加订阅链接完整性检查和解析，以解决订阅链接节点的JSON格式不完整原因而导致订阅失败，比如以下订阅链接：
https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
https://raw.githubusercontent.com/snakem982/proxypool/main/source/v2ray.txt

luci-app-ssr-plus: Fix `Hysteria2` subscribe and Add subscribe link complet check and parse.

---

v2raya/Makefile

fix the hash

---

xray-core/Makefile

xray-core: update to 25.4.30

---

xray-core/Makefile

xray-core: update to 25.6.8

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

添加自动更新的订阅检测，有变化才更新。
避免无更新时模块的重启。

luci-app-ssr-plus: Add subscribe link detection. Without update do not restart service.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

特别注意：根据 shadow-tls 的官方说明，`ss+shadow-tls` 仅支持 `ss-rust` ,不支持 `ss-libev`。订阅代码中我已写入代码控制，如果是  `ss-libev` 订阅时将报错。

luci-app-ssr-plus: Fix and add `ss+shadow-tls` new format subscribe.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/templates/ssr-plus.pot
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

See: https://xtls.github.io/config/transport.html#tlsobject

luci-app-ssr-plus: support xray ech
