luci-app-ssr-plus/root/usr/bin/ssr-switch

The default `ping` uses ICMP. While servers may block it.
Moreover, the GFW blocks specific port instead of the whole ip now. This commit benefits those port-blocked servers as well.

fix: use `tcpping` to test ICMP blocked server

---

luci-app-ssr-plus/root/usr/bin/ssr-switch

Fix #93 
`tcpping` (#37 ) may go through the proxy, showing 100% packet loss. So put it after the `ipset add ss_spec_wan_ac`.
`ipset` cannot accept domain directly. So transform it to IP.

Fixed automatic switch exception

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

**Fix /usr/share/shadowsocksr/subscribe.lua:362: attempt to concatenate field 'alias' (a nil value)**

Fix subscribe.lua:'alias' (a nil value)

---

luci-app-ssr-plus/po/zh_Hans

fix symbolic link of i18n

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Previous commit changed the udp port to 1357, but the VMess/VLESS port in config left unchanged. This PR fixes the udp issues when using VMess/VLESS.

Fix typo: fix VMess/VLESS udp issue

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Since port 9418 is used while cloning repositories with git:// protocol, it need to be proxied. See https://docs.github.com/en/enterprise-server@2.21/admin/configuration/network-ports#application-ports-for-end-users for more info.

Add port 9418 for cloning repositories using git:// protocol

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Disable IPv6 queries only for proxied domains. All other queries will not be affected.

disable pdnsd ipv6 query

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

Fix the problem of empty items in tls and xtls configuration

Fix the problem of empty items in tls and xtls configuration

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

Trojan and V2ray are 2 different protocols which should be interpreted separately.

Fix misinterpretation of trojan subscription

---

luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

1. Fix VLESS http/2 bug.
VLESS链接中的type是http，但Luci中的值为h2，这里做了一个判断修改。
2. Make the behavior of import VLESS link and VLESS subscribe the same
VLESS导入链接和订阅之间默认值有一些不同，这里修改使它们的行为大致相同。

Fix VLESS http/2 bug & Make the behavior of import VLESS link and VLESS subscribe the same

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

After installing procps-ng-ps, the ps command is not killing process when restarting. The consquence is there will be too many xray or v2ray process started which leads to a broken proxied network. To avoid this, we make ssr-plus to explicitly use busybox ps program.
Sample output from _procps-ng-ps_ version "ps -w"
[root@openwrt:~]$ ps -w
PID TTY          TIME CMD
13311 pts/0    00:00:00 bash
14224 pts/0    00:00:00 ps
Sample output from _busybox_ version "ps -w"
[root@openwrt:~]$ /bin/busybox ps -w
PID USER       VSZ STAT COMMAND
...
4424 root     4805m S    /var/etc/ssrplus/bin/v2ray -config /var/etc/ssrplus/tcp-only-ssr-retcp.json
5341 nobody    1980 S    /var/etc/ssrplus/bin/pdnsd -c /var/etc/ssrplus/pdnsd.conf
...
Sample output of ps symbolic link.
[root@openwrt:~]$ ll /bin/ps …

make it compatible with other ps program

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

If subscribe contains two identical addresses, this address will be added twice.

Avoiding redundancy address adding multiple times.

---

luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm
luci-app-ssr-plus/luasrc/view/shadowsocksr/socket.htm
luci-app-ssr-plus/po/zh-cn/ssr-plus.po

1. 当正在使用该节点时，将Apply改为Reapply。
2. 使用curl取代nixio.socket()来测试websocket连接：因为websocket可以使用path(ws_path)来区分服务，nixio.socket()只能测试端口是否连通，但无法测试websocket服务是否正常。
使用curl测试websocket的教程：[Test a WebSocket using curl](https://gist.github.com/htp/fbce19069187ec1cc486b594104f01d0)

Use curl instead of socket when transport is "ws; Change "Apply "to "Reapply" when the node is used

---

luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua

Allow curl to proceed handling an insecure server connection
有些节点使用自签名或过期的ssl/tls证书，导致curl无法继续运行，所以添加参数`-k`忽略证书校验错误
fix #561

fix(luci-app-ssr-plus): Add the '-k' param to the curl command

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

SS SIP008 subscription uses pure JSON like this:
```json
[{
"remarks": "SS SIP008",
"server": "127.0.0.1",
"server_port": 8388,
"method": "aes-128-gcm",
"password": "password",
"plugin": "obfs-local",
"plugin_opts": "obfs=tls;obfs-host=example.com"
}]
```

luci-app-ssr-plus: support ss sip008 subscription

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

Fix up reject ipv6 cache issues

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

This patch caused the #615 and #612 issues.
Before fixing the PDNSD ipv6 filter mode, users can use dnsmasq reject ipv6 mode instead.

luci-app-ssr-plus: revert commit #610

---

luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus

luci-nginx和luci-ssl-nginx使用了uwsgi作为web服务器，uwsgi默认配置中使用`limit-as`限制了虚拟内存的大小为1000m，然而xray申请的虚拟内存为4803m左右，导致在luci中restart或reload shadowsocksr失效。所以修改`limit-as`的值为5000

fix restart/reload when use luci-nginx

---

luci-app-ssr-plus/Makefile
v2ray-plugin/Makefile

移除对libustream-openssl 的依赖。
在kconfig中添加Include libustream-ssl菜单。
不过没有对` libustream-ssl`形成依赖关系，虽然会根据`CONFIG_DEFAULT_libustream_xxxssl=y`默认选择，但是可能会因没有`CONFIG_DEFAULT_libustream_xxxssl=y`或手动取消导致没有编译libustream-ssl。

remove depend libustream-openssl & add "Include libustream-ssl" to kconfig

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

增加了个节点alias中的关键词保留匹配
* 大概逻辑为
* 字段为空：不启用这个功能
* 字段不为空：使用`/`切分关键词，只要存在一个就保留
* 已测试（均符合预期）
* 为空
* 一个（没有`/`）
* 三个
初次写lua，代码不是特别规范aha，但是测试了至少能满足需要了~

luci-app-ssr-plus: add save checking and filtering for server alias

---

luci-app-ssr-plus/Makefile

修复`config PACKAGE_$(PKG_NAME)_INCLUDE_libustream-mbedtls`导致的错误。
没有先git commit再做测试，测试完之后，感觉bool "Use libustream-xxx"不太好，改为了"Include libustream-xxx"，结果还改错地方了，又感觉只改了一个标题应该没啥，改完后没做测试。。。 又一次教训😢

修复make 错误fix config PACKAGE_$(PKG_NAME)_INCLUDE_libustream-mbedtls

---

luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm

页面加载完毕后，再开始‘ping’请求。
`ping`请求耗时较大些，可能会阻塞后续的页面加载，所以放在页面加载完毕后再执行。

After the page is loaded, the 'ping' request starts

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

草，后面的两个commit怎么也被自动合并进来了😂算了 那就一块吧
1，支持 Xray-core 的 H2/gRPC 健康检查功能，详见[此处](https://github.com/XTLS/Xray-core/pull/633#issuecomment-878989087)
2，新增选项，用于调整 **initial_windows_size** 。这个参数可以帮助解决gRPC在通过CloudFlare时出现的断流问题，具体的说明见[文档](https://github.com/XTLS/Xray-docs-next/blob/130ad7437dc0dcf57f0b23825e15ef00f18b2b8b/docs/config/transports/grpc.md#grpcobject)。对应 Xray-core 的commit在 [这里](https://github.com/XTLS/Xray-core/commit/63da3a548138640f96e631f10d6e2ee1bae3ed62)
3，新增选框 Bloom Filter，以支持 Xray-core v1.5.1 中的 Shadowsocks 安全增强功能，可能对防范重放攻击[有所帮助](https://github.com/XTLS/Xray-core/issues/625#issuecomment-962390112)。实际测试下，这个功能在服务端/客户端单边启用不会导致 '明显的' 兼容性问题，所以我将它默认设置为开；更多说明请见[Xray的releases页面](https://github.com/XTLS/Xray-core/releases/tag/v1.5.1)
4，这个算是我夹带的私货了 XD …

Add health check for h2 & gRPC

---

luci-app-ssr-plus/root/usr/bin/ssr-rules

Openwrt使用`device`取代了`ifname`，虽然为了兼容，Openwrt会在路由器开机时为lan、wan等接口生成`ifname`属性，但是因为脚本顺序问题，可能出现 “在ssr启动后才生成`ifname`” 的情况。

Add the device attribute of getting  interface

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po

对于没有设置 maxEarlyData、earlyDataHeaderName ws 参数的 v2ray 服务端，ssrp 默认添加前置数据会导致节点无法连接，添加选项按需启用打破这种尴尬

luci-app-ssr-plus: ws: add enable early data option

---

chinadns-ng/Makefile
luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/bin/ssr-monitor

ChinaDNS-NG 是一个解决 DNS 污染的轻量级方案。
如今 DNS 污染日益严重，GFWList 内置的域名已然更不上 GFW 的更新，目前仅 v2ray / xray 和 ssr 支持域名嗅探，并且存在国内 DNS 返回保留地址的问题。
引入 ChinaDNS-NG 可以极大程度上缓解该问题，但由于所有请求均会先往国内 DNS 发送（GFWList 中的域名除外），故存在所谓“DNS 泄露”，由用户自行决定是否使用。

luci-app-ssr-plus: add chinadns-ng support

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

Fast Open can shave off one RTT for every connection at the cost of the correct semantics of SOCKS5/HTTP/TUN protocols. When enabled, the client will always accept a connection immediately without confirming with the server that its destination is reachable. If the server then fails to connect or rejects the connection, the client will just close it without sending any data.

luci-app-ssr-plus: support Hysteria Fast Open

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

当订阅`vless`时，如果使用了新流控，security 应该为`tls`，然而并没有设置对应的`tls_flow`。因此生成 config 的时候会丢失 `flow`

Update subscribe.lua -- add  missing `tls_flow`

---

hysteria/Makefile

I think, first upgrade hysteria to 2 to solve the current compilation error problem. As for luci, it can be improved later.
@coolsnowwolf what do you think

hysteria: update ot 2.0.4

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
shadow-tls/Makefile

1.support Hysteria Version 2 full features, remove Hysteria v1 features
2.support tuic full functions for ssr-plus, fixed tuic minor errors and bugs
3.add shadow-tls new features, support full fuctions for ssr-plus

Support hysteria v2, and Add shadow-tls features

---

shadowsocksr-libev/Makefile

https://github.com/openssl/openssl/issues/11847

Add libopenssl-legacy to fix chipher failure on openwrt 23 with openssl 3.0

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

传输 (Transport)
transport 用于自定义 QUIC 连接使用的底层协议。目前唯一可用的类型是 udp，保留类型选项是为了将来可能添加的其他类型。
```
transport:
type: udp
udp:
hopInterval: 30s 
`````

luci-app-ssr-plus: Fix `Hysteria2` failure to start problem

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

MUX生成的配置如下
```jsonc
"mux": {
"enabled": true,
"concurrency": -1, // -1表示不启用TCP MUX，作为默认值
"xudpConcurrency": 16, // 表示启用 UDP MUX，默认值16
"xudpProxyUDP443": "reject" // 阻止 UDP 443 流量，默认值
}
```
当普通用户选中MUX时，使用这套默认值是最佳设置。
用户勾选 MPTCP 时
配置文件生成如下内容。取消勾选则不生成
```
"sockopt": {
"tcpcongestion": "bbr",
"tcpMptcp": true,
"tcpNoDelay": true
},
```

luci-app-ssr-plus: add Xray-core `xudpConcurrency` `xudpProxyUDP443` `tcpcongestion` `tcpMptcp` `tcpNoDelay`

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

优化修改情况：
1、取消端口跳跃时点击“保存和应用”无效，在右上角必须再次保存和应用，此修改修复此问题；
2、启用端口跳跃时，自动隐藏了节点原来配置的单端口，导致服务器列表为乱码字符且无法`ping`延迟和无法看到节点测试显示是否`ok`，此修改实现仍然显示节点端口。
3、此修改仍然显示节点端口并启用端口跳跃时，配置能改为端口跳跃设置的端口范围，如取消端口跳跃，配置改为节点端口；
4、增加可配置使用`apln`;
截图为设置端口跳跃后显示原单端口和`ping`值：
截图为设置端口跳跃的界面：

luci-app-ssr-plus: Optimal `hysteria2` allocation

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr

目前`Hhysteria2`运行后会在日志中显示一大串涉及`Hhysteria2`的相关内容，看起来很凌乱不直观。
修改前的效果图：
修改后的效果图：

luci-app-ssr-plus: Only in log display `Hhysteria2` version number

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

`sniffing` 默认值 enable
`domainsExcluded` 默认值 true
`routeOnly` 默认值 false
`domainsExcluded` from:
https://github.com/XTLS/Xray-core/discussions/364#discussion-3268358
https://github.com/xiaorouji/openwrt-passwall2/pull/8#issue-1167437739

luci-app-ssr-plus: add Xray `sniffing`(enable/disable) `domainsExcluded` `routeOnly`

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

1. 将 VLESS 中的 `流控（Flow）`默认值调整为 `xtls-rprx-vision` ，新增一个值 `none`，对话框调整为不允许用户输入自定义内容
2. 将指纹伪造默认值调整为 `chrome` ，`禁用`移至最后
3. Mux中的 `TCP 最大并发连接数` 默认值`-1`，翻译为`禁用（disable）`，不允许用户输入自定义内容，另一个选项是 `8`。以减少普通用户不会调遇错机率。
4. Mux中的 `UDP 最大并发连接数` 默认值`16`，第2个选项是值是`-1`，`禁用（disable）`，禁用后按Xray文档讲的SS就是用协议本身规定的原生UDP，trojan协议就是UoT行为。不允许用户输入自定义内容。以减少普通用户不会调遇错机率。
5. 新增加 `Xray DNS 功能` 和 `Xray 日志功能`，由于新手水平，只做了固定选项让用户选的模式，对话框都不允许用户输入自定义内容，以减少输错后Xray配置出错启动失败机率。使用时把 `DNS 解析方式` 改为 使用本机5335的DNS服务即可。但是要用户手动上传geosite.dat文件。
`远端 DNS 域名列表`指 `geosite:geolocation-!cn` 分类中的域名，使用远端 DNS查询，远端DNS是`走代理`发送请求到服务端。剩下没命中的域名，使用国内DNS直连出站查询（DoH）。

luci-app-ssr-plus: add Xray `DNS` `Log` Setting options Simplifying `Mux` Options

---

shadowsocksr-libev/Makefile
shadowsocksr-libev/patches/105-Upgrade-PCRE-to-PCRE2.patch
shadowsocksr-libev/src/server/Makefile.in
shadowsocksr-libev/src/server/rule.c
shadowsocksr-libev/src/server/rule.h

* shadowsocksr-libev: Upgrade PCRE to PCRE2

shadowsocksr-libev: Upgrade PCRE2 & drop libopenssl-legacy depends

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

***  Add WireGuard `kernelMode` `keepAlive` `allowedIPs` ` reserved` argument
***  whether to use the virtual NIC TUN of the Linux kernel！Virtual NIC TUN of Linux kernel can be used only when system supports and have root permission.
Some routes cannot be connected if they are used.
*** Current Wireguard protocol `outbound` Is not supported `streamSettings`.
*** fix `WireGuard protocol` failure to connect problem.

luci-app-ssr-plus: fix `WireGuard protocol` failure to connect problem.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh-cn/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

1、If the listening socket is not set to dual-stack, the socket behavior depends on the platform. 
2、Settings for the local inbound socks5 server should be set to [::] for proper running after the dual-stack configuration.
See official WIKI:
https://github.com/EAimTY/tuic/tree/dev/tuic-client
**效果图：**

luci-app-ssr-plus: Fix `TUIC` does not run or cannot connect.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

The heartbeat interval should be configured, incorrectly configured to `Timeout`.

luci-app-ssr-plus: Fixing misconfigurations

---

luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

Re-open PR:
1、已完美修复Xray更新到2024.9.30版本后，无法连接服务器导致不能科学上网问题；
2、本次修改已完美兼容1.8.24及以下版本，即使服务端节点为旧版本也正常使用。
3、本次修改已完美修改socks 的配置用以适配新旧Xray版本，如socks使用非主服务器，单独生成配置，
如socks使用主服务器，生成的socks配置在主服务器的配置中。
4、WireGuard 配置：替换kernelMode为noKernelTun，见：https://github.com/XTLS/Xray-core/commit/9bdf72d658cc3bd168374d2997b93299603c87af
效果图：
生成的配置部分内容：
非主服务器的socks部分配置：
主服务器部分配置：

luci-app-ssr-plus: Fix link failure for latest Xray version.

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua

Fixed: https://github.com/fw876/helloworld/commit/c82145f45e34bba827e71cee7ac3ad0bc2732a95
经测试，本人遇到的特殊情况是指新固件升级后（概率问题），在ssrp正常运行再手动更新gfw数据库时，系统日志中出现无法找到dnsmasq.cfg01411c*目录的报错而导致gfw数据库文件拷贝失败，再次手动更新后却又正常。本pr已修复此问题。

luci-app-ssr-plus: update.lua: Fix path configuration failure caused by whitespace characters in special cases.

---

luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm

luci-app-ssr-plus: Fix tcp protocol imported to Vmess node. Do not select TLS.

---

luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus

新增Xray的分片功能后，如使用的还是旧配置，会导致ssrp不能运行，此PR解决此问题。

luci-app-ssr-plus: Fix `Xray` old configuration does not run.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/status.lua
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua

说明：apple 域名解析dns可以修改为任意dns且可以为未来有新的apple域名时可以自由选择更新。
此pr为：https://github.com/fw876/helloworld/pull/1615   的重开，原pr太凌乱。

luci-app-ssr-plus: Add `apple domains data` update settings and replace `apple DNS` support.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
luci-app-ssr-plus/root/usr/share/shadowsocksr/shadowsocksr.config

实际使用中，除非特殊情况下，订阅和数据库没必要日日更新。
此次已兼容旧配置。

luci-app-ssr-plus: Add update time choose.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

*** 在导入启用TLS或reality但无流量控制参数的节点时，默认仍导入flow，从而导致节点无法正常代理。同时tcp或raw传输协议配置应调整为无http和有http情况下的对应配置。
***  彻底修复导入 `Xray` 的 `vless` 各种传输协议配置时总是有个别参数无法按预期导入的bug。
***  合并`TCP`、`RAW`传输协议，不再区分旧版`TCP`和新版`RAW`，新旧版节点配置统一使用`RAW`传输协议。

luci-app-ssr-plus: Fix flow control and TCP/RAW transport protocol configurations issues.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua

luci-app-ssr-plus: servers.lua: Fix when auto update is canceled opton is empty error.

---

luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

See: https://github.com/XTLS/Xray-core/commit/a2b773135a860f63e990874c551b099dfc888471
兼容旧版服务器节点。

luci-app-ssr-plus: WS: Forbid "host" in "headers", read "serverName" instead

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/status.lua
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po

*** 用于手动更新数据库后直接重启以便应用新的数据库，解决需停止服务再启动服务的操作问题，当然也可以用于日常的重启需要。

luci-app-ssr-plus: status.lua: Add `restart Service` button.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

*** 修改 `fingerprint` 为默认禁用，有效解决节点的 `fingerprint` 在保存后自动改为 `chrome` ，如再次保存节点，将改变节点实际的 `fingerprint` 值的问题，此修改在保存后仍默认节点的 `fingerprint` 值。
*** 此PR为： https://github.com/fw876/helloworld/pull/1637  重开。

luci-app-ssr-plus: Fix Xray's and Trojan's trojan protocol configuration import and subscribe issue.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

优化和改进的是：将服务器中的停用剥离，改为在界面中使用 **`启用`** 按钮处理（即：勾选时 **`启用`**，不勾选时 **`停用`** ），服务器中正常展示服务器中的节点信息。同时停用时仍默认为设置的服务器节点，以便后续继续使用，如需更改为其他节点，下拉选择并启用即可。
**Xray的功能新增见：**
https://github.com/XTLS/Xray-core/commit/5af90684c44d88036b99fbd441f3ad96847992a2
https://xtls.github.io/config/inbounds/socks.html#inboundconfigurationobject

luci-app-ssr-plus: Optimize and improve `socks` and add some features for Xray's `socks`.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

See: https://github.com/XTLS/Xray-core/discussions/4113
说明：本次新增的 `XHTTP` 传输协议，在使用新版本的Xray情况下，可将旧版本节点的 `SplitHTTP` 传输协议修改为新版本的 `XHTTP` 传输协议，但旧版本的Xray只能使用 `SplitHTTP` 传输协议，因此暂不删除旧版本的`SplitHTTP` 传输协议支持。
**新版Xray使用旧版  `SplitHTTP` 协议改为 `XHTTP` 传输协议后的效果图（已修改为 `XHTTP` 传输协议）：**

luci-app-ssr-plus: Add Xray new version `XHTTP` transport (formerly `SplitHTTP` transport) support.

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/init.d/shadowsocksr

目前 V2ray 等相关节点在开启分流后，不能使用socks5全局的password，会导致分流失败，此PR已修复。
原打算将奈飞分流使用的dns可以认证（dns2socks支持身份认证），但因mosdns不支持，没办法只能改为全部不需认证。
感谢TG群友“H”的贡献。

luci-app-ssr-plus: Fix when `SOCKS` enable password auth `Netflix` shunt failed issue.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

1、如ssrp不存在对应VPS服务器的插件时（比如：服务器使用的是Cloak插件，但ssrp没有该插件），可通过自定义设置插件路径和参数，以便SSRP能使用节点正常代理。
2、不选择自定义时，页面不显示自定义插件路径。
**效果图：**

luci-app-ssr-plus: Add `SS` plug custom Settings.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gfw2ipset.sh

同时优化代码使用while方式读取列表文件 防止 /etc/ssrplus/ 目录下的 black.list white.list deny.list 等2个或多个文件一行中存在空格 比如:# abc.com 而丢失：server。
感谢TG群友“H”的贡献。

luci-app-ssr-plus: Fix disable shunt mode `Netflix` list domain name unavailable.

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client.lua
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/status.lua
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/bin/ssr-monitor

添加的chinadns-ng用于国外dns解析的原因是：按照作者所说主要是新版chinadns-ng深度优化了性能以及内存占用，所以内存占用更小且性能更强。

luci-app-ssr-plus: Add `chinadns-ng` proxy parse.

---

luci-app-ssr-plus/Makefile
luci-app-ssr-plus/root/etc/init.d/shadowsocksr
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua

经部分用户测试，使用wget存在新旧版本兼容性问题，从而存在可能导致订阅失败现象。因此，干脆将使用wget替换为使用curl，以解决wget新旧版本可能存在不兼容现象。

luci-app-ssr-plus: Use 'wget-ssl' - > 'curl' to solve the compatibility issue between the old and new versions of wget.

---

luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

如下格式，其密码部分在bsae64解码后为URL编码格式，需使用URL编码进行解码才是真实的密码：
```
ss://MjAyMi1ibGFrZTMtYWVzLTEyOC1nY206WEdXbmhjUFAxb0Z4SXdxRXpRYXBnUSUzRCUzRCUzQTRuWHRlc0w2QnFOZlEyTVh2dnBqdGclM0QlM0Q@test.com:10333/?group=test#grose7ym
ss://MjAyMi1ibGFrZTMtYWVzLTEyOC1nY206MHB0T3l2VXhkTUg4OGdRNy9FeGN4dz09OmtXblhqdFNUOW5GcGdFQ3krNVBJa1E9PQ@xxx.com:32552#test
````

luci-app-ssr-plus: Add `ss` new format `URL encode` subscribe.

---

.github/workflows/multi-arch-test-build.yml
luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
luci-app-ssr-plus/po/templates/ssr-plus.pot
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua
luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua

说明：该功能为后续新的验证机制做准备。
See: https://github.com/XTLS/Xray-core/pull/4915

luci-app-ssr-plus: Add resistant quantum `ML-DSA-65` signature verify mechanism.

---

luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
luci-app-ssr-plus/po/templates/ssr-plus.pot
luci-app-ssr-plus/po/zh_Hans/ssr-plus.po
luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua

See: https://github.com/XTLS/Xray-core/pull/4998

luci-app-ssr-plus: Freedom: Add `maxSplit` fragment option; Add `applyTo` noises option

---

trojan/Makefile
trojan/boost-version.mk
trojan/patches/001-force-openssl-version.patch
trojan/patches/002-Fix-boost1.89-build.patch

**boost 1.89 versions: Boost.System is now a header-only library.**

trojan: Fix boost 1.89 ver build.
